apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gsd-workspace
  namespace: lk-gsd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gsd-home
  namespace: lk-gsd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 5Gi
