apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gsd-remote.fullname" . }}-home
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gsd-remote.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
